name: b_net
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.2+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.0.0
  table_calendar: ^3.1.2
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  image: ^4.3.0
  video_player: ^2.5.1
  cloud_functions: ^5.1.3 
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  font_awesome_flutter: 10.7.0
  badges: ^3.1.2 
  file_picker: ^9.0.2
  flutter_colorpicker: ^1.0.3
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.5 
  in_app_purchase: ^3.2.1
  purchases_flutter: ^8.7.0
  flutter_keyboard_visibility: ^6.0.0
  fl_chart: ^0.66.0
  shared_preferences: ^2.5.3
  gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/default_avatar.png
    - assets/default_team_avatar.png
    - assets/pitcher.png
    - assets/logo.png
    - assets/stadium.png
    - assets/Subscription_personal1month.png
    - assets/Subscription_personal12month.png
    - assets/Subscription_teamGold.png
    - assets/Subscription_teamGold12month.png
    - assets/Subscription_teamPlatina.png
    - assets/Subscription_teamPlatina12month.png
    - assets/icon.png
    - assets/icon-sp.png

flutter_launcher_icons:
  android: true
  ios: true

  image_path_android: "assets/icon-android.png"
  image_path_ios: "assets/icon.png"

  remove_alpha_ios: true